const paises = [
    'French Polynesia',
    'Saint Martin',
    'Venezuela',
    'Réunion',
    'El Salvador',
    'Dominica',
    'Gibraltar',
    'Kenya',
    'Brazil',
    'Maldives',
    'United States',
    'Cook Islands',
    'Niue',
    'Seychelles',
    'Central African Republic',
    'Tokelau',
    'Vanuatu',
    'Gambia',
    'Guyana',
    'Falkland Islands',
    'Belgium',
    'Western Sahara',
    'Turkey',
    'Saint Vincent and the Grenadines',
    'Pakistan',
    'Åland Islands',
    'Iran',
    'Indonesia',
    'New Zealand',
    'Afghanistan',
    'Guam',
    'Albania',
    'DR Congo',
    'Ivory Coast',
    'Sudan',
    'Timor-Leste',
    'Luxembourg',
    'Saudi Arabia',
    'Cambodia',
    'Nepal',
    'French Guiana',
    'Malaysia',
    'Rwanda',
    'Thailand',
    'Antarctica',
    'Jordan',
    'Switzerland',
    'Comoros',
    'Kosovo',
    'Isle of Man',
    'Montenegro',
    'Hong Kong',
    'Jersey',
    'Tajikistan',
    'Bulgaria',
    'Egypt',
    'Malawi',
    'Cape Verde',
    'Benin',
    'Morocco',
    'Ireland',
    'Moldova',
    'Denmark',
    'Turkmenistan',
    'Micronesia',
    'Monaco',
    'Barbados',
    'Algeria',
    'French Southern and Antarctic Lands',
    'Eritrea',
    'Lesotho',
    'Tanzania',
    'Mali',
    'Niger',
    'Andorra',
    'United Kingdom',
    'Germany',
    'United States Virgin Islands',
    'Somalia',
    'Sint Maarten',
    'Cameroon',
    'Dominican Republic',
    'Guinea',
    'Namibia',
    'Montserrat',
    'South Georgia',
    'Senegal',
    'Bouvet Island',
    'Solomon Islands',
    'France',
    'Saint Helena, Ascension and Tristan da Cunha',
    'Macau',
    'Argentina',
    'Bosnia and Herzegovina',
    'Anguilla',
    'Guernsey',
    'Djibouti',
    'Saint Kitts and Nevis',
    'Syria',
    'Puerto Rico',
    'Peru',
    'San Marino',
    'Australia',
    'New Caledonia',
    'Jamaica',
    'Kazakhstan',
    'Sierra Leone',
    'Palau',
    'South Korea',
    'Saint Pierre and Miquelon',
    'Belize',
    'Papua New Guinea',
    'Iceland',
    'American Samoa',
    'Burkina Faso',
    'Portugal',
    'Taiwan',
    'Japan',
    'China',
    'Lebanon',
    'Sri Lanka',
    'Guatemala',
    'Serbia',
    'Madagascar',
    'Eswatini',
    'Romania',
    'Antigua and Barbuda',
    'Curaçao',
    'Zambia',
    'Zimbabwe',
    'Tunisia',
    'United Arab Emirates',
    'Mongolia',
    'Norway',
    'Greenland',
    'Uruguay',
    'Bahamas',
    'Russia',
    'British Virgin Islands',
    'Wallis and Futuna',
    'Chad',
    'Saint Lucia',
    'Yemen',
    'United States Minor Outlying Islands',
    'Sweden',
    'Svalbard and Jan Mayen',
    'Laos',
    'Latvia',
    'Colombia',
    'Grenada',
    'Saint Barthélemy',
    'Canada',
    'Heard Island and McDonald Islands',
    'India',
    'Guinea-Bissau',
    'North Macedonia',
    'Paraguay',
    'Croatia',
    'Costa Rica',
    'Uganda',
    'Caribbean Netherlands',
    'Bolivia',
    'Togo',
    'Mayotte',
    'Marshall Islands',
    'North Korea',
    'Netherlands',
    'British Indian Ocean Territory',
    'Malta',
    'Mauritius',
    'Norfolk Island',
    'Honduras',
    'Spain',
    'Estonia',
    'Kyrgyzstan',
    'Chile',
    'Bermuda',
    'Equatorial Guinea',
    'Liberia',
    'Pitcairn Islands',
    'Libya',
    'Liechtenstein',
    'Vatican City',
    'Christmas Island',
    'Oman',
    'Philippines',
    'Poland',
    'Faroe Islands',
    'Bahrain',
    'Belarus',
    'Slovenia',
    'Guadeloupe',
    'Qatar',
    'Vietnam',
    'Mauritania',
    'Singapore',
    'Georgia',
    'Burundi',
    'Nauru',
    'South Sudan',
    'Samoa',
    'Cocos (Keeling) Islands',
    'Republic of the Congo',
    'Cyprus',
    'Kuwait',
    'Trinidad and Tobago',
    'Tuvalu',
    'Angola',
    'Tonga',
    'Greece',
    'Mozambique',
    'Myanmar',
    'Austria',
    'Ethiopia',
    'Martinique',
    'Azerbaijan',
    'Uzbekistan',
    'Bangladesh',
    'Armenia',
    'Nigeria',
    'South Africa',
    'Brunei',
    'Italy',
    'Finland',
    'Israel',
    'Aruba',
    'Nicaragua',
    'Haiti',
    'Kiribati',
    'Turks and Caicos Islands',
    'Cayman Islands',
    'Ukraine',
    'Mexico',
    'Palestine',
    'Fiji',
    'Slovakia',
    'Ghana',
    'Suriname',
    'Cuba',
    'Bhutan',
    'Hungary',
    'São Tomé and Príncipe',
    'Iraq',
    'Czechia',
    'Lithuania',
    'Northern Mariana Islands',
    'Botswana',
    'Panama',
    'Gabon',
    'Ecuador',
]
export default paises
